# Generated by Django 4.0.4 on 2022-05-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('publishDate', models.DateTimeField(verbose_name='发行时间')),
                ('rating', models.SmallIntegerField(verbose_name='评分')),
                ('type', models.CharField(max_length=200, verbose_name='种类')),
            ],
        ),
    ]
