# Generated by Django 4.0.4 on 2022-07-05 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='标题')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='作者')),
                ('publishDate', models.DateField(blank=True, null=True, verbose_name='发行时间')),
                ('rating', models.SmallIntegerField(blank=True, null=True, verbose_name='评分')),
                ('type', models.CharField(blank=True, max_length=200, verbose_name='种类')),
            ],
        ),
        migrations.CreateModel(
            name='BoundJournalList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='业务日期')),
                ('journalType', models.CharField(max_length=20, verbose_name='单据类型')),
                ('journalNumber', models.CharField(max_length=60, verbose_name='单据编号')),
                ('number', models.CharField(max_length=10, verbose_name='货品编号')),
                ('type', models.CharField(max_length=50, verbose_name='货品类别')),
                ('name', models.CharField(max_length=500, verbose_name='货品名称')),
                ('specification', models.CharField(max_length=50, verbose_name='规格型号')),
                ('unit', models.CharField(max_length=10, verbose_name='单位')),
                ('inboundCount', models.PositiveIntegerField(blank=True, null=True, verbose_name='入库数量')),
                ('inboundAmount', models.PositiveIntegerField(blank=True, null=True, verbose_name='入库金额')),
                ('outboundCount', models.PositiveIntegerField(blank=True, null=True, verbose_name='出库数量')),
                ('outboundAmount', models.PositiveIntegerField(blank=True, null=True, verbose_name='出库金额')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='货品编号')),
                ('type', models.CharField(max_length=50, verbose_name='货品类别')),
                ('name', models.CharField(max_length=500, verbose_name='货品名称')),
                ('specification', models.CharField(max_length=50, verbose_name='规格型号')),
                ('unit', models.CharField(max_length=10, verbose_name='单位')),
                ('inventoryQuantity', models.PositiveIntegerField(default=0, verbose_name='库存数量')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='货品类别')),
                ('number', models.CharField(max_length=10, verbose_name='货品编号')),
                ('name', models.CharField(max_length=500, verbose_name='货品名称')),
                ('specification', models.CharField(max_length=50, verbose_name='规格型号')),
                ('unit', models.CharField(max_length=10, verbose_name='单位')),
                ('pic', models.CharField(max_length=500, verbose_name='货品图片')),
                ('purchasePrice', models.PositiveIntegerField(default=0, verbose_name='参考进价')),
                ('sellingPrice', models.PositiveIntegerField(default=0, verbose_name='参考售价')),
                ('minInventoryQuantity', models.PositiveIntegerField(default=0, verbose_name='库存数量')),
                ('maxInventoryQuantity', models.PositiveIntegerField(default=0, verbose_name='库存数量')),
                ('remark', models.CharField(max_length=200, verbose_name='参考进价')),
            ],
        ),
        migrations.CreateModel(
            name='sqlStatementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='SQL语句名称')),
                ('sysType', models.CharField(choices=[('renshi', 'renshi'), ('xiaoshou', 'xiaoshou'), ('kaoqing', 'kaoqing')], default='renshi', max_length=200, verbose_name='SQL所属系统')),
                ('type', models.CharField(choices=[('sear', 'search'), ('up', 'update'), ('a', 'add'), ('rem', 'remove')], default='sear', max_length=10, verbose_name='SQL操作类型')),
                ('enable', models.BooleanField(verbose_name='启用状态')),
                ('sqlStatment', models.TextField(verbose_name='SQL语句')),
                ('sqlExplanation', models.TextField(verbose_name='SQL注释说明')),
            ],
        ),
        migrations.CreateModel(
            name='sqlSingleStatmentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sqlStatment', models.TextField(verbose_name='SQL语句')),
                ('sqlExplanation', models.TextField(verbose_name='SQL注释说明')),
                ('author', models.CharField(default='未知作者', max_length=100, verbose_name='作者')),
                ('sqlID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.sqlstatementdocument')),
            ],
        ),
    ]
