# Generated by Django 4.0.4 on 2022-07-06 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sqlstatementdocument',
            name='sqlExplanation',
        ),
        migrations.RemoveField(
            model_name='sqlstatementdocument',
            name='sqlStatment',
        ),
    ]
