# Generated by Django 4.0.4 on 2022-06-06 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='未知', max_length=100, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishDate',
            field=models.DateTimeField(null=True, verbose_name='发行时间'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.SmallIntegerField(default=0, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(default='未定义', max_length=200, verbose_name='种类'),
        ),
    ]
