# Generated by Django 4.0.4 on 2022-07-06 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_remove_sqlstatementdocument_sqlexplanation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlsinglestatmentlist',
            name='sqlID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sqls', to='app01.sqlstatementdocument'),
        ),
    ]
