# Generated by Django 4.0.4 on 2022-06-06 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_book_author_alter_book_publishdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='未知作者', max_length=100, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='未定义标题', max_length=500, verbose_name='标题'),
        ),
    ]
