# Generated by Django 4.0.4 on 2022-07-06 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_sqlsinglestatmentlist_sqlid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sqlsinglestatmentlist',
            options={'ordering': ['-id']},
        ),
    ]
