# Generated by Django 4.0.4 on 2022-06-15 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_book_author_alter_book_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='goodsInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='货品编号')),
                ('type', models.CharField(max_length=50, verbose_name='货品类别')),
                ('name', models.CharField(max_length=500, verbose_name='货品名称')),
                ('specification', models.CharField(max_length=50, verbose_name='规格型号')),
                ('unit', models.CharField(max_length=10, verbose_name='单位')),
                ('inventoryQuantity', models.PositiveIntegerField(default=0, verbose_name='库存数量')),
            ],
        ),
    ]
