# Generated by Django 4.0.4 on 2022-07-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_alter_sqlsinglestatmentlist_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sqlsinglestatmentlist',
            name='author',
        ),
        migrations.AddField(
            model_name='sqlstatementdocument',
            name='lastestSqlExplanation',
            field=models.TextField(default='', verbose_name='SQL注释说明'),
        ),
        migrations.AddField(
            model_name='sqlstatementdocument',
            name='lastestSqlStatment',
            field=models.TextField(default='', verbose_name='SQL语句'),
        ),
    ]
