# Generated by Django 4.0.4 on 2022-06-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_goodsinventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='货品类别')),
                ('number', models.CharField(max_length=10, verbose_name='货品编号')),
                ('name', models.CharField(max_length=500, verbose_name='货品名称')),
                ('specification', models.CharField(max_length=50, verbose_name='规格型号')),
                ('unit', models.CharField(max_length=10, verbose_name='单位')),
                ('pic', models.CharField(max_length=500, verbose_name='货品图片')),
                ('purchasePrice', models.PositiveIntegerField(default=0, verbose_name='参考进价')),
                ('sellingPrice', models.PositiveIntegerField(default=0, verbose_name='参考售价')),
                ('minInventoryQuantity', models.PositiveIntegerField(default=0, verbose_name='库存数量')),
                ('maxInventoryQuantity', models.PositiveIntegerField(default=0, verbose_name='库存数量')),
                ('remark', models.CharField(max_length=200, verbose_name='参考进价')),
            ],
        ),
    ]
