# Generated by Django 4.0.4 on 2022-07-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_remove_sqlsinglestatmentlist_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='path',
            field=models.CharField(default=123, max_length=3000, verbose_name='路径'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sqlstatementdocument',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='启用状态'),
        ),
        migrations.AlterField(
            model_name='sqlstatementdocument',
            name='lastestSqlExplanation',
            field=models.TextField(default='', verbose_name='最新SQL注释说明'),
        ),
        migrations.AlterField(
            model_name='sqlstatementdocument',
            name='lastestSqlStatment',
            field=models.TextField(default='', verbose_name='最新SQL语句'),
        ),
    ]
