# Generated by Django 4.0.4 on 2022-07-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_book_path_alter_sqlstatementdocument_enable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='path',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='路径'),
        ),
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='种类'),
        ),
    ]
