# Generated by Django 4.0.4 on 2022-06-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_boundjournallist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundjournallist',
            name='inboundAmount',
            field=models.PositiveIntegerField(null=True, verbose_name='入库金额'),
        ),
        migrations.AlterField(
            model_name='boundjournallist',
            name='inboundCount',
            field=models.PositiveIntegerField(null=True, verbose_name='入库数量'),
        ),
        migrations.AlterField(
            model_name='boundjournallist',
            name='outboundAmount',
            field=models.PositiveIntegerField(null=True, verbose_name='出库金额'),
        ),
        migrations.AlterField(
            model_name='boundjournallist',
            name='outboundCount',
            field=models.PositiveIntegerField(null=True, verbose_name='出库数量'),
        ),
    ]
