# Generated by Django 4.0.4 on 2022-06-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_alter_boundjournallist_inboundamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundjournallist',
            name='date',
            field=models.DateTimeField(verbose_name='业务类型'),
        ),
    ]
