# Generated by Django 4.0.4 on 2022-06-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_alter_boundjournallist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=100, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishDate',
            field=models.DateField(blank=True, null=True, verbose_name='发行时间'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, max_length=500, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(blank=True, max_length=200, verbose_name='种类'),
        ),
    ]
