# Generated by Django 4.0.4 on 2022-06-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_alter_book_author_alter_book_publishdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundjournallist',
            name='date',
            field=models.DateTimeField(verbose_name='业务日期'),
        ),
        migrations.AlterField(
            model_name='boundjournallist',
            name='inboundAmount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='入库金额'),
        ),
        migrations.AlterField(
            model_name='boundjournallist',
            name='inboundCount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='入库数量'),
        ),
        migrations.AlterField(
            model_name='boundjournallist',
            name='outboundAmount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='出库金额'),
        ),
        migrations.AlterField(
            model_name='boundjournallist',
            name='outboundCount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='出库数量'),
        ),
    ]
