# Generated by Django 4.0.4 on 2022-06-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_alter_boundjournallist_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundjournallist',
            name='journalNumber',
            field=models.CharField(max_length=50, verbose_name='单据编号'),
        ),
        migrations.AlterField(
            model_name='boundjournallist',
            name='journalType',
            field=models.CharField(max_length=20, verbose_name='单据类型'),
        ),
    ]
