# Generated by Django 4.0.4 on 2022-06-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_alter_boundjournallist_journalnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='sqlStatementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='SQL语句名称')),
                ('type', models.CharField(choices=[('sear', 'search'), ('up', 'update'), ('a', 'add'), ('rem', 'remove')], default='sear', max_length=10, verbose_name='SQL操作类型')),
                ('enable', models.BooleanField(verbose_name='启用状态')),
                ('sqlStatment', models.TextField(verbose_name='SQL语句')),
                ('sqlExplanation', models.TextField(verbose_name='SQL注释说明')),
            ],
        ),
    ]
