# Generated by Django 4.0.4 on 2022-06-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_sqlstatementdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlstatementdocument',
            name='sysType',
            field=models.CharField(choices=[('renshi', 'renshi'), ('xiaoshou', 'xiaoshou'), ('kaoqing', 'kaoqing')], default='renshi', max_length=200, verbose_name='SQL所属系统'),
        ),
    ]
