# Generated by Django 4.0.4 on 2022-12-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookLibPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folderPath', models.CharField(blank=True, max_length=3000, null=True, verbose_name='文件夹路径')),
            ],
        ),
    ]
